// Scans src/app/api/**/route.ts and writes standalone/gen/routes.ts: the in-browser "server" calls these very handlers.
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const apiDir = path.join(root, "src/app/api");
const found = [];
(function walk(dir) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else if (e.name === "route.ts") found.push(p);
  }
})(apiDir);
found.sort();
const lines = ["// GENERATED by standalone/gen-routes.mjs – do not edit", ""];
found.forEach((f, i) => lines.push(`import * as r${i} from "@/app/api/${path.relative(apiDir, f).replace(/\\/g, "/").replace(/\.ts$/, "")}";`));
lines.push("", "export const ROUTES: Array<{ pattern: string; mod: Record<string, unknown> }> = [");
found.forEach((f, i) => {
  const rel = path.relative(apiDir, path.dirname(f)).replace(/\\/g, "/");
  lines.push(`  { pattern: "/api${rel ? "/" + rel : ""}", mod: r${i} as Record<string, unknown> },`);
});
lines.push("];", "");
fs.writeFileSync(path.join(import.meta.dirname, "gen/routes.ts"), lines.join("\n"));
console.log(`routes.ts: ${found.length} API routes`);
